name: practica_ui_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/logo.png
    - images/volcan.jpg

flutter_native_splash:
  color: "#ffffff"
  image: images/logo.jpeg  
  color_dark: "#6D6A6A"
  image_dark: images/logo.jpeg

  android_12:
    image: images/logo.jpeg
    icon_background_color: "#ffffff"
    image_dark: images/logo.jpeg
    icon_background_color_dark: "#121212"

  web: false    




  
